"""
backend/routes/report_routes.py

Report generation and export endpoints:
- POST   /reports                      — generate a new report for a dataset
- GET    /reports                      — list current user's reports
- GET    /reports/{public_id}          — get a single report's metadata
- GET    /reports/{public_id}/download — download the generated report file
- DELETE /reports/{public_id}          — delete a report and its file
"""

import os
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from loguru import logger
from sqlalchemy.orm import Session

from backend.auth import get_current_user
from backend.config import get_settings
from backend.database import get_db
from backend.models import Dataset, DatasetStatus, Report, User
from backend.schemas import MessageResponse, ReportCreateRequest, ReportResponse
from backend.services.report_generator import generate_report

router = APIRouter()
settings = get_settings()


def _get_ready_owned_dataset_or_404(dataset_public_id: str, current_user: User, db: Session) -> Dataset:
    """Fetches a dataset owned by the current user, ensuring it's READY for use."""
    dataset = (
        db.query(Dataset)
        .filter(Dataset.public_id == dataset_public_id, Dataset.owner_id == current_user.id)
        .first()
    )
    if dataset is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Dataset not found.")
    if dataset.status != DatasetStatus.READY:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Dataset is not ready (status: {dataset.status.value}).",
        )
    return dataset


def _get_owned_report_or_404(public_id: str, current_user: User, db: Session) -> Report:
    """
    Fetches a report by public_id, ensuring it belongs to a dataset owned
    by the current user (via a join through Dataset).
    """
    report = (
        db.query(Report)
        .join(Dataset, Report.dataset_id == Dataset.id)
        .filter(Report.public_id == public_id, Dataset.owner_id == current_user.id)
        .first()
    )
    if report is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found.")
    return report


@router.post("", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
def create_report(
    payload: ReportCreateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Report:
    """
    Generates a new report (PDF/Excel/CSV) summarizing a dataset's key
    statistics and charts, and saves it to disk.

    Raises:
        404 if the dataset doesn't exist / isn't owned by this user.
        400 if the dataset isn't ready.
        500 if report generation fails unexpectedly.
    """
    dataset = _get_ready_owned_dataset_or_404(payload.dataset_public_id, current_user, db)

    reports_dir = Path(settings.REPORTS_DIR)
    reports_dir.mkdir(parents=True, exist_ok=True)

    try:
        file_path = generate_report(
            dataset=dataset,
            title=payload.title,
            report_format=payload.format,
            upload_dir=settings.UPLOAD_DIR,
            reports_dir=str(reports_dir),
        )
    except Exception as exc:
        logger.error(f"Report generation failed for dataset {dataset.public_id}: {exc}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Report generation failed. Please try again.",
        ) from exc

    report = Report(
        dataset_id=dataset.id,
        title=payload.title,
        format=payload.format,
        file_path=file_path,
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    logger.info(f"Report generated by {current_user.email}: {payload.title} ({payload.format.value})")
    return report


@router.get("", response_model=list[ReportResponse])
def list_reports(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> list[Report]:
    """Lists all reports belonging to datasets owned by the current user."""
    return (
        db.query(Report)
        .join(Dataset, Report.dataset_id == Dataset.id)
        .filter(Dataset.owner_id == current_user.id)
        .order_by(Report.created_at.desc())
        .all()
    )


@router.get("/{public_id}", response_model=ReportResponse)
def get_report(
    public_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Report:
    """Retrieves metadata for a single report."""
    return _get_owned_report_or_404(public_id, current_user, db)


@router.get("/{public_id}/download")
def download_report(
    public_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> FileResponse:
    """
    Downloads the actual generated report file (PDF/Excel/CSV).

    Raises:
        404 if the report metadata exists but the file is missing from disk
        (e.g. manually deleted, or a deployment volume issue).
    """
    report = _get_owned_report_or_404(public_id, current_user, db)

    file_path = Path(report.file_path)
    if not file_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report file is missing from storage.",
        )

    media_type_map = {
        "pdf": "application/pdf",
        "excel": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "csv": "text/csv",
    }
    media_type = media_type_map.get(report.format.value, "application/octet-stream")

    return FileResponse(
        path=file_path,
        media_type=media_type,
        filename=file_path.name,
    )


@router.delete("/{public_id}", response_model=MessageResponse)
def delete_report(
    public_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> MessageResponse:
    """Deletes a report's database record and its underlying file on disk."""
    report = _get_owned_report_or_404(public_id, current_user, db)

    file_path = Path(report.file_path)
    if file_path.exists():
        os.remove(file_path)

    db.delete(report)
    db.commit()

    logger.info(f"User {current_user.email} deleted report: {report.title}")
    return MessageResponse(detail=f"Report '{report.title}' has been deleted.")